// <auto-generated />
using System;
using FreeBirds.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreeBirds.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250415083342_UpdatePasswordToHashed")]
    partial class UpdatePasswordToHashed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FreeBirds.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Password = "$2a$11$IA1SWZw/3/ly37z/o3wjze8MDNnse5ND6TcKHkixOmfqR9csa7rrO",
                            Username = "testuser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
